//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommentId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string ParentType { get; set; }
        public string CommentTitle { get; set; }
        public string CommentText { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AutoAudit_CreatedDate { get; set; }
        public string AutoAudit_CreatedBy { get; set; }
        public Nullable<System.DateTime> AutoAudit_ModifiedDate { get; set; }
        public string AutoAudit_ModifiedBy { get; set; }
        public Nullable<int> AutoAudit_RowVersion { get; set; }
    }
}
