//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public System.Guid ConfigurationId { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigVal { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string ParentEntity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
