//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExpenseTrackerEntities : DbContext
    {
        public ExpenseTrackerEntities()
            : base("name=ExpenseTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<PickListItem> PickListItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleFeature> RoleFeatures { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
    
        public virtual ObjectResult<Feature> usp_GetMenu(Nullable<System.Guid> pRoleId, Nullable<System.Guid> pUserId)
        {
            var pRoleIdParameter = pRoleId.HasValue ?
                new ObjectParameter("pRoleId", pRoleId) :
                new ObjectParameter("pRoleId", typeof(System.Guid));
    
            var pUserIdParameter = pUserId.HasValue ?
                new ObjectParameter("pUserId", pUserId) :
                new ObjectParameter("pUserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Feature>("usp_GetMenu", pRoleIdParameter, pUserIdParameter);
        }
    
        public virtual ObjectResult<Feature> usp_GetMenu(Nullable<System.Guid> pRoleId, Nullable<System.Guid> pUserId, MergeOption mergeOption)
        {
            var pRoleIdParameter = pRoleId.HasValue ?
                new ObjectParameter("pRoleId", pRoleId) :
                new ObjectParameter("pRoleId", typeof(System.Guid));
    
            var pUserIdParameter = pUserId.HasValue ?
                new ObjectParameter("pUserId", pUserId) :
                new ObjectParameter("pUserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Feature>("usp_GetMenu", mergeOption, pRoleIdParameter, pUserIdParameter);
        }
    }
}
