//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public System.Guid ExpenseId { get; set; }
        public string ExpenseTitle { get; set; }
        public string ExpenseDetail { get; set; }
        public Nullable<System.DateTime> ExpenseTimeStamp { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> AutoAudit_CreatedDate { get; set; }
        public string AutoAudit_CreatedBy { get; set; }
        public Nullable<System.DateTime> AutoAudit_ModifiedDate { get; set; }
        public string AutoAudit_ModifiedBy { get; set; }
        public Nullable<int> AutoAudit_RowVersion { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual User User { get; set; }
    }
}
