//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickListItem
    {
        public System.Guid PickListItemId { get; set; }
        public string DisplayText { get; set; }
        public string DisplayCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ParentTypeCode { get; set; }
    }
}
