//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.RoleFeatures = new HashSet<RoleFeature>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public bool IsEditAllowed { get; set; }
        public Nullable<System.DateTime> AutoAudit_CreatedDate { get; set; }
        public string AutoAudit_CreatedBy { get; set; }
        public Nullable<System.DateTime> AutoAudit_ModifiedDate { get; set; }
        public string AutoAudit_ModifiedBy { get; set; }
        public Nullable<int> AutoAudit_RowVersion { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleFeature> RoleFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
