//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Tracker.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.Expenses = new HashSet<Expens>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public string UserContactNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public Nullable<System.Guid> ForgetPasswordCode { get; set; }
        public string LAST_ACCESS_IP { get; set; }
        public Nullable<System.DateTime> AutoAudit_CreatedDate { get; set; }
        public string AutoAudit_CreatedBy { get; set; }
        public Nullable<System.DateTime> AutoAudit_ModifiedDate { get; set; }
        public string AutoAudit_ModifiedBy { get; set; }
        public Nullable<int> AutoAudit_RowVersion { get; set; }
        public string ProfilePic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
    }
}
